/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Boards
         * @description The boards available on the new-game screen.
         */
        get: operations["list_boards_boards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rulesets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rulesets
         * @description Both rulesets, expanded and labelled, so the UI can show what Kids Mode actually changes.
         *
         *     Returns ``RulesetView`` rather than the raw ``Ruleset`` since MON-417 (G-36): each setting
         *     arrives with its ``label_key`` and a ``differs_from_universal`` the engine decided, which is
         *     what deleted the setup screen's client-side diff and its hand-kept label map.
         */
        get: operations["list_rulesets_rulesets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Game
         * @description Start a game and return the opening view. Any bot moves stream in behind it.
         */
        post: operations["create_game_games_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Game
         * @description Restore a saved game — the body is exactly what ``GET /games/{id}/save`` returned.
         *
         *     The body is read raw rather than declared as a ``SaveFile`` parameter, for two reasons
         *     carried forward from the MON-100 security review:
         *
         *     * **Size.** This is the only route whose body is not a small fixed shape, so it gets an
         *       explicit ceiling instead of reading whatever arrives — enforced *while* reading, by
         *       :func:`_read_bounded`, not after.
         *     * **Every load failure is one key.** A stale ``schema_version`` raises ``ValueError``
         *       (pydantic wraps it), but a save naming an unknown board raises ``BoardDataError``,
         *       which is *not* a ``ValueError`` — pydantic lets it through, and as a declared body
         *       parameter it escaped as a 500 with a traceback. Validating inside the handler is what
         *       lets both become ``error.save_schema_mismatch``.
         *
         *     ``if_exists`` is the answer to a question the player was asked *after* being refused once
         *     (ADR-011): it defaults to ``refuse``, so a client that has never heard of it gets the same 409
         *     it always got rather than silently ending somebody's game.
         *
         *     The OpenAPI request body is declared by hand above, so the contract still says ``SaveFile``
         *     and ``generated.ts`` still types it.
         */
        post: operations["load_game_games_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Game
         * @description The current view. Safe to poll, and the reconnect path for the UI.
         *
         *     ``since`` is the event cursor (G-34). Omit it for state only; ``since=0`` replays the
         *     whole game, which is what a reconnecting client wants.
         */
        get: operations["get_game_games__game_id__get"];
        put?: never;
        post?: never;
        /** Delete Game */
        delete: operations["delete_game_games__game_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Save Game
         * @description The complete state, RNG and deck order included — the save file.
         *
         *     This is the *only* route that returns hidden information, which is the whole of
         *     ADR-008 §2: "the JSON is the save file" survives without being conflated with what a
         *     client may see while playing.
         *
         *     Since ADR-011 the file is an envelope — the state *and* the session's log — because a session is
         *     more than a ``GameState`` and a restored game with no history was the half of that nobody noticed.
         */
        get: operations["save_game_games__game_id__save_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Command
         * @description Apply one command, then let the bots answer it. The only way a game changes.
         *
         *     ``async`` on purpose: it puts the handler on the event loop, so appending to a live
         *     WebSocket subscriber's queue (MON-303) happens on the loop's own thread rather than from
         *     a thread-pool worker. MON-304 relies on the same thing — the bot driver awaits between moves,
         *     and a handler off the loop could not yield to let those pushes drain.
         */
        post: operations["submit_command_games__game_id__commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Command
         * @description Ask whether a command would be accepted, changing nothing (G-32).
         *
         *     An illegal command is a 200 with ``legal: false`` here, not a 422 — the trade builder
         *     asks this on every keystroke, and "not valid yet" is a normal answer, not an error.
         */
        post: operations["validate_command_games__game_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket event stream
         * @description Handshake for the WebSocket event stream. Each frame after the upgrade is one LoggedEvent; `since` replays the backlog from a cursor. Not a JSON GET — the operation is declared so the frame type reaches the generated client (MON-303).
         */
        get: operations["game_event_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuctionEnded */
        AuctionEnded: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "auction_ended";
            /** Lot */
            lot: components["schemas"]["TileLot"] | components["schemas"]["BuildingLot"];
            /** Winner */
            winner?: number | null;
            /**
             * Price
             * @default 0
             */
            price: number;
        };
        /**
         * AuctionFrame
         * @description A live auction.
         *
         *     The lot is a :class:`~kesef_engine.primitives.TileLot` or
         *     :class:`~kesef_engine.primitives.BuildingLot` rather than a tile index, because the
         *     building-shortage rule auctions a *house*; ``queue`` holds the rest of an estate being
         *     liquidated after a bankruptcy to the bank (GAP G-3).
         */
        AuctionFrame: {
            resume: components["schemas"]["Phase"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "auction";
            /** Lot */
            lot: components["schemas"]["TileLot"] | components["schemas"]["BuildingLot"];
            reason: components["schemas"]["AuctionReason"];
            /** Eligible */
            eligible: number[];
            /**
             * Active
             * @default []
             */
            active: number[];
            /** Turn */
            turn?: number | null;
            /**
             * High Bid
             * @default 0
             */
            high_bid: number;
            /** High Bidder */
            high_bidder?: number | null;
            /**
             * Min Bid
             * @default 1
             */
            min_bid: number;
            /** Max Bid */
            max_bid?: number | null;
            /**
             * Queue
             * @default []
             */
            queue: (components["schemas"]["TileLot"] | components["schemas"]["BuildingLot"])[];
        };
        /** AuctionFrameView */
        AuctionFrameView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "auction";
            resume: components["schemas"]["Phase"];
            /** Lot */
            lot: components["schemas"]["TileLot"] | components["schemas"]["BuildingLot"];
            reason: components["schemas"]["AuctionReason"];
            /** Eligible */
            eligible: number[];
            /**
             * Active
             * @default []
             */
            active: number[];
            /** Turn */
            turn?: number | null;
            /** High Bid */
            high_bid: number;
            /** High Bidder */
            high_bidder?: number | null;
            /** Min Bid */
            min_bid: number;
            /** Max Bid */
            max_bid?: number | null;
            /**
             * Queue
             * @default []
             */
            queue: (components["schemas"]["TileLot"] | components["schemas"]["BuildingLot"])[];
            /** Withdrawn */
            withdrawn: number[];
        };
        /**
         * AuctionMinimum
         * @description What a lot may first be bid at (MON-712).
         *
         *     ``NONE`` is the printed rule: no reserve, so a square can go for ₪1 (spec §3.6 trap 5).
         *     ``LIST_PRICE`` puts the floor at the deed's own printed price, which turns the auction from
         *     "who wants this cheap" into "does anybody else want it at the sticker price".
         *
         *     The owner's report is why this exists: playing with a child, the child bid ₪1 on every square
         *     the adult declined and won them all. The no-reserve rule assumes bidders who compete; between a
         *     parent and a six-year-old there is no competition to hold the price up, so the rule that makes
         *     the auction interesting between adults makes it a giveaway across a generation gap.
         *
         *     A *floor*, deliberately, and not a fixed price. The bidding above it is unchanged — the minimum
         *     increment is still one, the decliner may still bid, the high bid still stands until beaten — so
         *     this is one number in :class:`~kesef_engine.state.AuctionFrame`, not a second auction.
         * @enum {string}
         */
        AuctionMinimum: "none" | "list_price";
        /**
         * AuctionReason
         * @description Why an auction opened. The continuation differs per cause, so it is stored.
         * @enum {string}
         */
        AuctionReason: "declined_purchase" | "bankruptcy_to_bank" | "building_shortage";
        /** AuctionStarted */
        AuctionStarted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "auction_started";
            /** Lot */
            lot: components["schemas"]["TileLot"] | components["schemas"]["BuildingLot"];
            reason: components["schemas"]["AuctionReason"];
            /** Eligible */
            eligible: number[];
        };
        /**
         * BankruptcyShare
         * @description One creditor's slice of a bankrupt estate, divided proportionally to claim (G-7).
         *
         *     Part of :class:`PlayerBankrupted`, not an event of its own — the estate divides once,
         *     in one act, and a per-creditor event would invite a reader to treat the halves as
         *     independent.
         */
        BankruptcyShare: {
            /** Creditor */
            creditor: number | "bank";
            /** Claim */
            claim: number;
            /**
             * Cash
             * @default 0
             */
            cash: number;
            /**
             * Tiles
             * @default []
             */
            tiles: number[];
            /**
             * Jail Cards
             * @default []
             */
            jail_cards: components["schemas"]["Deck"][];
        };
        /** BidPlaced */
        BidPlaced: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bid_placed";
            /** Player */
            player: number;
            /** Amount */
            amount: number;
        };
        /** BidderWithdrew */
        BidderWithdrew: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "bidder_withdrew";
            /** Player */
            player: number;
        };
        /**
         * BoardSummary
         * @description Board metadata for the new-game screen. Names arrive as keys; the UI translates.
         */
        BoardSummary: {
            /** Id */
            id: string;
            /** Name Key */
            name_key: string;
            /** Tile Count */
            tile_count: number;
            /** Ownable Count */
            ownable_count: number;
            /** Catalogue Ready */
            catalogue_ready: boolean;
        };
        /**
         * BoardView
         * @description The whole board: static per game, ~4 KB, and the reason a client can draw anything
         *     at all (G-30 — before ADR-008 no endpoint returned a single tile).
         */
        BoardView: {
            /** Id */
            id: string;
            /** Name Key */
            name_key: string;
            /** Tiles */
            tiles: components["schemas"]["TileView"][];
            /** Catalogue Ready */
            catalogue_ready: boolean;
            /** Go To Jail Target */
            go_to_jail_target: number;
        };
        /**
         * BotLevel
         * @description How hard a bot plays. Single-sourced here because the engine's ``PlayerKind``,
         *     the bot protocol and the server's seat configuration all need the same three names.
         * @enum {string}
         */
        BotLevel: "easy" | "normal" | "hard";
        /**
         * BuildHouse
         * @description Build one house (or the hotel, on the fifth) on ``tile``.
         */
        BuildHouse: {
            /** Player */
            player: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "build_house";
            /** Tile */
            tile: number;
        };
        /** BuildingChanged */
        BuildingChanged: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "building_changed";
            /** Tile */
            tile: number;
            /** Houses */
            houses: number;
            /** Delta */
            delta: number;
            /**
             * Level
             * @enum {string}
             */
            level: "house" | "hotel";
        };
        /**
         * BuildingLot
         * @description One house or hotel from a bank that has run short of them.
         *
         *     Bidders want it for their own tile, so the lot names no tile — which is exactly why
         *     ``AuctionState.tile: TileIndex`` could not express this auction (GAP G-3).
         */
        BuildingLot: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "building";
            /**
             * Building
             * @enum {string}
             */
            building: "house" | "hotel";
        };
        /**
         * BuyProperty
         * @description Buy the tile you are standing on at its list price.
         */
        BuyProperty: {
            /** Player */
            player: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "buy_property";
        };
        /** CancelTrade */
        CancelTrade: {
            /** Player */
            player: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "cancel_trade";
        };
        /** CardDrawn */
        CardDrawn: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "card_drawn";
            /** Player */
            player: number;
            deck: components["schemas"]["Deck"];
            /** Card Id */
            card_id: string;
        };
        /**
         * CardFrame
         * @description A drawn card that has not finished resolving.
         *
         *     ``step`` is what makes "advance to the nearest utility, then pay ten times the dice"
         *     resumable when the payment opens a debt halfway through (GAP G-9).
         */
        CardFrame: {
            resume: components["schemas"]["Phase"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "card";
            /** Card Id */
            card_id: string;
            deck: components["schemas"]["Deck"];
            /**
             * Step
             * @default 0
             */
            step: number;
        };
        /**
         * CardFrameView
         * @description A verbatim copy. The whole stack ships, so a half-resolved card stays face-up under
         *     the debt dialog sitting on top of it (G-9).
         */
        CardFrameView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "card";
            resume: components["schemas"]["Phase"];
            /** Card Id */
            card_id: string;
            deck: components["schemas"]["Deck"];
            /** Step */
            step: number;
        };
        /**
         * CashChanged
         * @description The single ledger entry. Every movement of money is exactly one of these.
         */
        CashChanged: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "cash_changed";
            /** Player */
            player: number;
            /** Delta */
            delta: number;
            reason: components["schemas"]["CashReason"];
            /** Balance */
            balance: number;
            /**
             * Counterparty
             * @default bank
             */
            counterparty: number | ("bank" | "free_parking_pot");
        };
        /**
         * CashReason
         * @description Why money moved. Drives both the UI narration and the money-conservation test.
         * @enum {string}
         */
        CashReason: "go_salary" | "rent" | "purchase" | "auction_win" | "tax" | "jail_fine" | "card" | "build" | "sell_building" | "mortgage" | "unmortgage" | "mortgage_transfer_fee" | "trade" | "bankruptcy_transfer" | "free_parking_pot";
        /**
         * ColorGroup
         * @description The eight buildable colour groups.
         *
         *     Rendering note for the UI: every group must also carry a *pattern or icon*, never
         *     colour alone — that serves both young children and colourblind players.
         * @enum {string}
         */
        ColorGroup: "brown" | "light_blue" | "pink" | "orange" | "red" | "yellow" | "green" | "dark_blue";
        /** CommandRequest */
        CommandRequest: {
            /** Command */
            command: components["schemas"]["RollDice"] | components["schemas"]["EndTurn"] | components["schemas"]["BuyProperty"] | components["schemas"]["DeclinePurchase"] | components["schemas"]["PlaceBid"] | components["schemas"]["WithdrawFromAuction"] | components["schemas"]["BuildHouse"] | components["schemas"]["SellHouse"] | components["schemas"]["MortgageProperty"] | components["schemas"]["UnmortgageProperty"] | components["schemas"]["ProposeTrade"] | components["schemas"]["RespondToTrade"] | components["schemas"]["CancelTrade"] | components["schemas"]["PayJailFine"] | components["schemas"]["UseJailCard"] | components["schemas"]["RollForJail"] | components["schemas"]["DeclareBankruptcy"];
        };
        /**
         * DebtFrame
         * @description What one player owes and cannot currently pay in cash.
         *
         *     ``obligations`` is plural because "pay each player ₪50" creates one debt with up to
         *     five creditors (GAP G-7). Semantics are shortfall-as-data: cash never goes negative,
         *     and the outstanding gross lives here.
         */
        DebtFrame: {
            resume: components["schemas"]["Phase"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "debt";
            /** Debtor */
            debtor: number;
            /** Obligations */
            obligations: components["schemas"]["Obligation"][];
            reason: components["schemas"]["CashReason"];
            /** Source Tile */
            source_tile?: number | null;
        };
        /** DebtFrameView */
        DebtFrameView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "debt";
            resume: components["schemas"]["Phase"];
            /** Debtor */
            debtor: number;
            /** Obligations */
            obligations: components["schemas"]["Obligation"][];
            reason: components["schemas"]["CashReason"];
            /** Source Tile */
            source_tile?: number | null;
            /** Total */
            total: number;
            /** Creditors */
            creditors: (number | "bank")[];
        };
        /** DebtIncurred */
        DebtIncurred: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "debt_incurred";
            /** Debtor */
            debtor: number;
            /** Creditor */
            creditor: number | "bank";
            /** Amount */
            amount: number;
        };
        /** DebtSettled */
        DebtSettled: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "debt_settled";
            /** Debtor */
            debtor: number;
            /** Creditor */
            creditor: number | "bank";
            /** Amount */
            amount: number;
        };
        /**
         * Deck
         * @description Which pile a card came from — and therefore which pile it must return to.
         * @enum {string}
         */
        Deck: "chance" | "community_chest";
        /**
         * DeckCounts
         * @description How many cards each pile holds. The *order* stays hidden — that is the whole of
         *     G-35: shipping the shuffled list told the client every card it was about to draw.
         */
        DeckCounts: {
            /** Chance */
            chance: number;
            /** Community Chest */
            community_chest: number;
        };
        /**
         * DeclareBankruptcy
         * @description Concede that the debt in the live :class:`~kesef_engine.state.DebtFrame` cannot be met.
         */
        DeclareBankruptcy: {
            /** Player */
            player: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "declare_bankruptcy";
        };
        /**
         * DeclinePurchase
         * @description Decline. Under the universal ruleset this opens an auction.
         */
        DeclinePurchase: {
            /** Player */
            player: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "decline_purchase";
        };
        /** DiceRolled */
        DiceRolled: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "dice_rolled";
            /** Player */
            player: number;
            /** First */
            first: number;
            /** Second */
            second: number;
            /** Total */
            total: number;
            /**
             * Doubles Streak
             * @default 0
             */
            doubles_streak: number;
            /**
             * Purpose
             * @default move
             * @enum {string}
             */
            purpose: "move" | "jail" | "rent";
        };
        /**
         * DiceState
         * @description The last roll. ``purpose`` matters: a card-driven utility rent roll is not a move,
         *     and a roll for doubles out of jail moves the token without granting another turn.
         *     Conflating the three made ``is_doubles`` lie (GAP G-10).
         */
        DiceState: {
            /** First */
            first: number;
            /** Second */
            second: number;
            /**
             * Purpose
             * @default move
             * @enum {string}
             */
            purpose: "move" | "jail" | "rent";
        };
        /**
         * DiceView
         * @description The last roll, carrying its own total and doubles flag (G-36).
         */
        DiceView: {
            /** First */
            first: number;
            /** Second */
            second: number;
            /**
             * Purpose
             * @enum {string}
             */
            purpose: "move" | "jail" | "rent";
            /** Total */
            total: number;
            /** Is Doubles */
            is_doubles: boolean;
        };
        /** EndTurn */
        EndTurn: {
            /** Player */
            player: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "end_turn";
            /** Elapsed Seconds */
            elapsed_seconds?: number | null;
        };
        /**
         * ErrorResponse
         * @description Every failure this API reports, in one shape (GAP G-33).
         *
         *     ``reason_key`` is an i18n key, never a sentence, and ``params`` carries the context the
         *     catalogue entry interpolates — which is what lets ``error.insufficient_funds`` say how
         *     much short. The engine's ``IllegalCommandError`` already carries both; before ADR-008
         *     the transport dropped the params on the floor.
         */
        ErrorResponse: {
            /**
             * Reason Key
             * @example error.not_your_turn
             */
            reason_key: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: number | string;
            };
        };
        /** GameEnded */
        GameEnded: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "game_ended";
            /** Winner */
            winner?: number | null;
            /**
             * Reason
             * @enum {string}
             */
            reason: "last_solvent" | "time_limit" | "concession" | "no_survivors";
            /**
             * Final Standings
             * @default []
             */
            final_standings: components["schemas"]["PlayerStanding"][];
        };
        /**
         * GameState
         * @description A complete game. See the module docstring for why this is one flat value.
         */
        GameState: {
            /**
             * Schema Version
             * @default 2
             */
            schema_version: number;
            /** Game Id */
            game_id: string;
            /** Board Id */
            board_id: string;
            ruleset: components["schemas"]["Ruleset"];
            /**
             * Locale
             * @default en
             */
            locale: string;
            rng: components["schemas"]["Rng"];
            /** Players */
            players: components["schemas"]["PlayerState"][];
            /** Properties */
            properties: components["schemas"]["PropertyState"][];
            /** @default awaiting_roll */
            phase: components["schemas"]["Phase"];
            /** Current Player Id */
            current_player_id: number;
            dice?: components["schemas"]["DiceState"] | null;
            /**
             * Doubles Streak
             * @default 0
             */
            doubles_streak: number;
            /**
             * Turn Number
             * @default 1
             */
            turn_number: number;
            /**
             * Interrupts
             * @default []
             */
            interrupts: (components["schemas"]["AuctionFrame"] | components["schemas"]["DebtFrame"] | components["schemas"]["TradeFrame"] | components["schemas"]["CardFrame"])[];
            /**
             * Chance Deck
             * @default []
             */
            chance_deck: string[];
            /**
             * Community Chest Deck
             * @default []
             */
            community_chest_deck: string[];
            /**
             * Free Parking Pot
             * @default 0
             */
            free_parking_pot: number;
            /**
             * Elapsed Seconds
             * @default 0
             */
            elapsed_seconds: number;
            /**
             * Elimination Order
             * @default []
             */
            elimination_order: number[];
            /** Winner */
            winner?: number | null;
        };
        /**
         * GameStateView
         * @description What the state carries, minus the hidden information, plus the derived facts.
         *
         *     Field order follows ``GameState`` so the two read side by side; the omissions and the
         *     promotions are enumerated in ``test_projection.py`` and checked mechanically.
         */
        GameStateView: {
            /** Schema Version */
            schema_version: number;
            /** Game Id */
            game_id: string;
            /** Board Id */
            board_id: string;
            ruleset: components["schemas"]["Ruleset"];
            /** Locale */
            locale: string;
            /** Players */
            players: components["schemas"]["PlayerView"][];
            /** Properties */
            properties: components["schemas"]["PropertyState"][];
            phase: components["schemas"]["Phase"];
            /** Current Player Id */
            current_player_id: number;
            dice?: components["schemas"]["DiceView"] | null;
            /** Doubles Streak */
            doubles_streak: number;
            /** Turn Number */
            turn_number: number;
            /**
             * Interrupts
             * @default []
             */
            interrupts: (components["schemas"]["AuctionFrameView"] | components["schemas"]["DebtFrameView"] | components["schemas"]["TradeFrameView"] | components["schemas"]["CardFrameView"])[];
            deck_counts: components["schemas"]["DeckCounts"];
            /** Free Parking Pot */
            free_parking_pot: number;
            /** Elapsed Seconds */
            elapsed_seconds: number;
            /**
             * Elimination Order
             * @default []
             */
            elimination_order: number[];
            /** Winner */
            winner?: number | null;
            /** Houses Remaining */
            houses_remaining: number;
            /** Hotels Remaining */
            hotels_remaining: number;
            /**
             * Rent Quotes
             * @default []
             */
            rent_quotes: (components["schemas"]["RentQuote"] | null)[];
        };
        /**
         * GameView
         * @description Everything a client needs to render one frame — a projection, not the state.
         *
         *     Bundling the legal commands with the state is what lets the UI stay rules-free: it
         *     renders the buttons it is handed instead of re-deriving them and drifting.
         */
        GameView: {
            board: components["schemas"]["BoardView"];
            state: components["schemas"]["GameStateView"];
            /** Legal Commands */
            legal_commands: (components["schemas"]["RollDice"] | components["schemas"]["EndTurn"] | components["schemas"]["BuyProperty"] | components["schemas"]["DeclinePurchase"] | components["schemas"]["PlaceBid"] | components["schemas"]["WithdrawFromAuction"] | components["schemas"]["BuildHouse"] | components["schemas"]["SellHouse"] | components["schemas"]["MortgageProperty"] | components["schemas"]["UnmortgageProperty"] | components["schemas"]["ProposeTrade"] | components["schemas"]["RespondToTrade"] | components["schemas"]["CancelTrade"] | components["schemas"]["PayJailFine"] | components["schemas"]["UseJailCard"] | components["schemas"]["RollForJail"] | components["schemas"]["DeclareBankruptcy"])[];
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["LoggedEvent"][];
            /**
             * Event Cursor
             * @default 0
             */
            event_cursor: number;
        };
        /**
         * GroupHoldings
         * @description One colour group as one player holds it (G-31/G-32) — a verbatim copy since MON-421.
         *
         *     Every number used to be "a copy or an engine call", and three of the six were the second kind
         *     only in the sense that they were arithmetic *beside* an engine call: ``owned``, ``houses`` and
         *     ``mortgaged_count`` were computed here from ``state.properties``, which made this the third
         *     copy of the ``properties[i].owner == player`` predicate while ``complete`` came from the
         *     engine. Half a row from the rules and half from a loop next to them is how the two halves end
         *     up able to disagree.
         *
         *     ``kesef_engine.state.GroupHoldings`` now answers all six, and this is the wire twin of it —
         *     declared rather than re-exported for the reason the module docstring gives: a view is a copy
         *     with an explicit, greppable shape, and ``test_projection.py`` checks the field-by-field parity
         *     mechanically.
         */
        GroupHoldings: {
            group: components["schemas"]["ColorGroup"];
            /** Owned */
            owned: number;
            /** Total */
            total: number;
            /** Complete */
            complete: boolean;
            /** Houses */
            houses: number;
            /** Mortgaged Count */
            mortgaged_count: number;
        };
        /**
         * HouseRules
         * @description What this table has agreed to change about the rules it is playing (MON-712).
         *
         *     Every field is optional and ``None`` means *leave the named rule set alone*, which is what makes
         *     this composable with Kids Mode: a kids game already has auctions off, and a house rule that said
         *     nothing about auctions must not turn them back on.
         *
         *     ## Why the product's default lives in the client and not here
         *
         *     The owner asked for auctions to be **off by default**, and the temptation is to spell that here,
         *     where every caller would inherit it. It is the wrong place. ``Ruleset.universal()`` is what this
         *     repository means by *correct* — the goldens replay against it and the invariant tests measure
         *     it — so a default that quietly diverged would make every one of them a record of a variant. The
         *     default belongs to whatever *decides which game to start*, which is the setup screen; the wire
         *     stays a faithful description of what was asked for.
         */
        HouseRules: {
            /** Auctions Enabled */
            auctions_enabled?: boolean | null;
            auction_minimum?: components["schemas"]["AuctionMinimum"] | null;
        };
        /**
         * IfExists
         * @description What ``POST /games/load`` should do when that save's ``game_id`` is already live (ADR-011).
         *
         *     The policy is a *request* field rather than something inferred from the body, and it defaults to
         *     :attr:`REFUSE` — so the unchanged request keeps answering the 409 it always did, and a client
         *     that has not been taught the question cannot silently end somebody's game.
         * @enum {string}
         */
        IfExists: "refuse" | "replace" | "copy";
        /** LeftJail */
        LeftJail: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "left_jail";
            /** Player */
            player: number;
            /**
             * Via
             * @enum {string}
             */
            via: "fine" | "card" | "doubles" | "time_served";
        };
        /**
         * LegalityView
         * @description ``POST /games/{id}/validate``'s answer — the engine's ``LegalityResult``, copied.
         *
         *     The trade builder validates a draft here rather than firing speculative commands and
         *     reading 422s (G-32); ADR-005 delegates trade legality to ``is_legal``, and without this
         *     route that delegation dead-ends at the HTTP boundary.
         */
        LegalityView: {
            /** Legal */
            legal: boolean;
            /** Reason Key */
            reason_key?: string | null;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: number | string;
            };
        };
        /**
         * LoggedEvent
         * @description One event with the session-assigned sequence number the store gave it (G-34).
         *
         *     The envelope lives on the transport, not on the event: ``seq`` is a fact about *this
         *     session's log*, and the engine — which has no session — must not have to invent one.
         *     The same envelope is what the WebSocket pushes (MON-303), so both transports carry one
         *     type and a reconnecting client can de-duplicate by ``seq``.
         */
        LoggedEvent: {
            /** Seq */
            seq: number;
            /** Event */
            event: components["schemas"]["TurnStarted"] | components["schemas"]["DiceRolled"] | components["schemas"]["TokenMoved"] | components["schemas"]["CashChanged"] | components["schemas"]["RentCharged"] | components["schemas"]["PropertyAcquired"] | components["schemas"]["AuctionStarted"] | components["schemas"]["BidPlaced"] | components["schemas"]["BidderWithdrew"] | components["schemas"]["AuctionEnded"] | components["schemas"]["CardDrawn"] | components["schemas"]["SentToJail"] | components["schemas"]["LeftJail"] | components["schemas"]["BuildingChanged"] | components["schemas"]["MortgageChanged"] | components["schemas"]["TradeProposed"] | components["schemas"]["TradeExecuted"] | components["schemas"]["TradeDeclined"] | components["schemas"]["TradeCancelled"] | components["schemas"]["DebtIncurred"] | components["schemas"]["DebtSettled"] | components["schemas"]["PlayerBankrupted"] | components["schemas"]["PhaseChanged"] | components["schemas"]["GameEnded"];
        };
        /** MortgageChanged */
        MortgageChanged: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "mortgage_changed";
            /** Player */
            player: number;
            /** Tile */
            tile: number;
            /** Mortgaged */
            mortgaged: boolean;
        };
        /** MortgageProperty */
        MortgageProperty: {
            /** Player */
            player: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "mortgage_property";
            /** Tile */
            tile: number;
        };
        /** NewGameRequest */
        NewGameRequest: {
            /** Seats */
            seats: components["schemas"]["SeatConfig"][];
            /**
             * Board Id
             * @default classic
             */
            board_id: string;
            /** @default universal */
            ruleset: components["schemas"]["RulesetName"];
            /** @default {} */
            house_rules: components["schemas"]["HouseRules"];
            /**
             * Locale
             * @default en
             */
            locale: string;
            /** Seed */
            seed?: number | null;
            /** Game Id */
            game_id?: string | null;
        };
        /**
         * Obligation
         * @description One creditor's share of a debt. The bank is named, not a ``None`` sentinel.
         */
        Obligation: {
            /** Creditor */
            creditor: number | "bank";
            /** Amount */
            amount: number;
        };
        /** PayJailFine */
        PayJailFine: {
            /** Player */
            player: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "pay_jail_fine";
        };
        /**
         * Phase
         * @enum {string}
         */
        Phase: "awaiting_roll" | "jail_decision" | "moving" | "resolving_tile" | "awaiting_purchase_decision" | "auction" | "card_resolution" | "debt_settlement" | "trade_review" | "awaiting_end_turn" | "game_over";
        /** PhaseChanged */
        PhaseChanged: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "phase_changed";
            previous: components["schemas"]["Phase"];
            current: components["schemas"]["Phase"];
        };
        /** PlaceBid */
        PlaceBid: {
            /** Player */
            player: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "place_bid";
            /** Amount */
            amount: number;
        };
        /** PlayerBankrupted */
        PlayerBankrupted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "player_bankrupted";
            /** Player */
            player: number;
            /** Creditor */
            creditor: number | "bank";
            /**
             * Tiles Transferred
             * @default []
             */
            tiles_transferred: number[];
            /**
             * Cash Transferred
             * @default 0
             */
            cash_transferred: number;
            /**
             * Jail Cards Transferred
             * @default []
             */
            jail_cards_transferred: components["schemas"]["Deck"][];
            /**
             * Shares
             * @default []
             */
            shares: components["schemas"]["BankruptcyShare"][];
        };
        /**
         * PlayerKind
         * @description Whether a seat is driven by a person or by a bot, and how strong the bot is.
         *
         *     ``bot_level`` is the only field: a separate ``is_bot`` flag was a second, independently
         *     settable source of the same truth, and ``bot_level: str`` accepted ``"banana"``
         *     (GAP G-19).
         */
        PlayerKind: {
            bot_level?: components["schemas"]["BotLevel"] | null;
        };
        /**
         * PlayerStanding
         * @description One line of the final table. Part of ``GameEnded``, not an event of its own.
         */
        PlayerStanding: {
            /** Player */
            player: number;
            /** Net Worth */
            net_worth: number;
            /** Rank */
            rank: number;
        };
        /** PlayerState */
        PlayerState: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            kind: components["schemas"]["PlayerKind"];
            /** Token */
            token: string;
            /**
             * Cash
             * @default 0
             */
            cash: number;
            /**
             * Position
             * @default 0
             */
            position: number;
            /**
             * In Jail
             * @default false
             */
            in_jail: boolean;
            /**
             * Jail Turns
             * @default 0
             */
            jail_turns: number;
            /**
             * Jail Cards
             * @default []
             */
            jail_cards: components["schemas"]["Deck"][];
            /**
             * Bankrupt
             * @default false
             */
            bankrupt: boolean;
            /**
             * Grammatical Gender
             * @default n
             * @enum {string}
             */
            grammatical_gender: "m" | "f" | "n";
        };
        /**
         * PlayerView
         * @description A seat, plus the four derived facts the dossier would otherwise re-derive.
         */
        PlayerView: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            kind: components["schemas"]["PlayerKind"];
            /** Token */
            token: string;
            /** Cash */
            cash: number;
            /** Position */
            position: number;
            /** In Jail */
            in_jail: boolean;
            /** Jail Turns */
            jail_turns: number;
            /** Jail Cards */
            jail_cards: components["schemas"]["Deck"][];
            /** Bankrupt */
            bankrupt: boolean;
            /**
             * Grammatical Gender
             * @enum {string}
             */
            grammatical_gender: "m" | "f" | "n";
            /** Net Worth */
            net_worth: number;
            /** Group Holdings */
            group_holdings: components["schemas"]["GroupHoldings"][];
            /** Tiles Owned */
            tiles_owned: number[];
            /** Is Bot */
            is_bot: boolean;
        };
        /** PropertyAcquired */
        PropertyAcquired: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "property_acquired";
            /** Player */
            player: number;
            /** Tile */
            tile: number;
            /** Price */
            price: number;
            /**
             * Via
             * @enum {string}
             */
            via: "purchase" | "auction" | "trade" | "bankruptcy";
        };
        /**
         * PropertyState
         * @description Ownership and development of one tile. Index-aligned with ``Board.tiles``.
         */
        PropertyState: {
            /** Owner */
            owner?: number | null;
            /**
             * Houses
             * @default 0
             */
            houses: number;
            /**
             * Mortgaged
             * @default false
             */
            mortgaged: boolean;
        };
        /** ProposeTrade */
        ProposeTrade: {
            /** Player */
            player: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "propose_trade";
            offer: components["schemas"]["TradeOffer"];
        };
        /**
         * RentCharged
         * @description Narration for a rent payment. The money itself moves in ``CashChanged``.
         *
         *     Everything needed to *explain* the figure is here, because "every rent figure can be
         *     explained, not merely charged" is a product gate and the explanation must survive in
         *     the log after the board has changed underneath it.
         *
         *     The explanation is inherited rather than restated: see :class:`RentQuote`.
         */
        RentCharged: {
            /** Owner */
            owner: number;
            /** Tile */
            tile: number;
            /** Amount */
            amount: number;
            /**
             * Base Rent
             * @default 0
             */
            base_rent: number;
            /**
             * Houses
             * @default 0
             */
            houses: number;
            /**
             * Multiplier
             * @default 1
             */
            multiplier: number;
            /** Dice Total */
            dice_total?: number | null;
            group?: components["schemas"]["ColorGroup"] | null;
            /**
             * Note Keys
             * @default []
             */
            note_keys: string[];
            /** Note Params */
            note_params?: {
                [key: string]: number | string;
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "rent_charged";
            /** Payer */
            payer: number;
        };
        /**
         * RentQuote
         * @description What a square charges, before anybody has landed on it (MON-420).
         *
         *     ``RentCharged`` is this shape plus *who paid*, and that is enforced structurally: the event
         *     inherits from here. Before MON-420 the multipliers lived only inside
         *     ``rules.rent._property_rent``, so the "explain this rent" affordance on the board and in the
         *     dossier had nothing to render and the UI's only options were to say nothing or to re-derive
         *     the tier ladder in TypeScript. One shape means the sentence a player reads *before* deciding
         *     is assembled from the same ``rent.note.*`` keys as the one they read in the log afterwards.
         *
         *     **A utility quote carries no amount.** Its rent is a multiple of a throw that has not
         *     happened, so ``amount`` and ``dice_total`` are both ``None`` and ``multiplier`` carries the
         *     figure the throw will be multiplied by — which is what ``rent.note.utility_quote`` says. An
         *     invented amount (the last roll's, or the average) would be a number the engine cannot stand
         *     behind, and is exactly the sort of plausible fiction the log's self-containment rule exists
         *     to prevent.
         */
        RentQuote: {
            /** Owner */
            owner: number;
            /** Tile */
            tile: number;
            /** Amount */
            amount?: number | null;
            /**
             * Base Rent
             * @default 0
             */
            base_rent: number;
            /**
             * Houses
             * @default 0
             */
            houses: number;
            /**
             * Multiplier
             * @default 1
             */
            multiplier: number;
            /** Dice Total */
            dice_total?: number | null;
            group?: components["schemas"]["ColorGroup"] | null;
            /**
             * Note Keys
             * @default []
             */
            note_keys: string[];
            /** Note Params */
            note_params?: {
                [key: string]: number | string;
            };
        };
        /** RespondToTrade */
        RespondToTrade: {
            /** Player */
            player: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "respond_to_trade";
            /** Accept */
            accept: boolean;
        };
        /**
         * Rng
         * @description A pure, seekable random stream.
         *
         *     ``stream`` separates independent uses of the same seed so that, for example,
         *     shuffling the Chance deck cannot shift the sequence of dice rolls.
         */
        Rng: {
            /** Seed */
            seed: number;
            /**
             * Counter
             * @default 0
             */
            counter: number;
            /**
             * Stream
             * @default 0
             */
            stream: number;
        };
        /** RollDice */
        RollDice: {
            /** Player */
            player: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "roll_dice";
        };
        /**
         * RollForJail
         * @description Attempt to roll doubles to leave jail.
         */
        RollForJail: {
            /** Player */
            player: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "roll_for_jail";
        };
        /**
         * RuleAbsentValue
         * @description No value at all — ``target_duration_minutes`` under the universal rules.
         *
         *     Its own case rather than a nullable number, because "no target length" and "a target length of
         *     zero" are different sentences and the model allows both.
         */
        RuleAbsentValue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "absent";
        };
        /** RuleFlagValue */
        RuleFlagValue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "flag";
            /** On */
            on: boolean;
        };
        /**
         * RuleFlagView
         * @description One setting, named, valued, and marked if this rule set changes it.
         */
        RuleFlagView: {
            /** Field */
            field: string;
            /** Label Key */
            label_key: string;
            /** Value */
            value: components["schemas"]["RuleFlagValue"] | components["schemas"]["RuleNumberValue"] | components["schemas"]["RuleNumberListValue"] | components["schemas"]["RuleAbsentValue"];
            /** Universal Value */
            universal_value: components["schemas"]["RuleFlagValue"] | components["schemas"]["RuleNumberValue"] | components["schemas"]["RuleNumberListValue"] | components["schemas"]["RuleAbsentValue"];
            /** Differs From Universal */
            differs_from_universal: boolean;
        };
        /** RuleNumberListValue */
        RuleNumberListValue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "numbers";
            /** Values */
            values: number[];
        };
        /** RuleNumberValue */
        RuleNumberValue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "number";
            /** Value */
            value: number;
        };
        /**
         * Ruleset
         * @description A complete, serialized rule configuration. Part of the saved game.
         */
        Ruleset: {
            name: components["schemas"]["RulesetName"];
            /**
             * Starting Cash
             * @default 1500
             */
            starting_cash: number;
            /**
             * Go Salary
             * @default 200
             */
            go_salary: number;
            /**
             * Jail Fine
             * @default 50
             */
            jail_fine: number;
            /**
             * Houses Available
             * @default 32
             */
            houses_available: number;
            /**
             * Hotels Available
             * @default 12
             */
            hotels_available: number;
            /**
             * Auctions Enabled
             * @default true
             */
            auctions_enabled: boolean;
            /** @default none */
            auction_minimum: components["schemas"]["AuctionMinimum"];
            /**
             * Mortgages Enabled
             * @default true
             */
            mortgages_enabled: boolean;
            /**
             * Trading Enabled
             * @default true
             */
            trading_enabled: boolean;
            /**
             * Even Build Enforced
             * @default true
             */
            even_build_enforced: boolean;
            /**
             * Building Shortage Auction
             * @default false
             */
            building_shortage_auction: boolean;
            /**
             * Max Jail Turns
             * @default 3
             */
            max_jail_turns: number;
            /**
             * Free Parking Pot Enabled
             * @default false
             */
            free_parking_pot_enabled: boolean;
            /**
             * Double Salary On Exact Go
             * @default false
             */
            double_salary_on_exact_go: boolean;
            /**
             * Hints Enabled
             * @default false
             */
            hints_enabled: boolean;
            /** Target Duration Minutes */
            target_duration_minutes?: number | null;
            /**
             * Simplified Trades
             * @default false
             */
            simplified_trades: boolean;
            /**
             * Starting Cash Denominations
             * @description Only for UI presentation of the cash tray; the engine tracks a single integer.
             * @default [
             *       500,
             *       100,
             *       50,
             *       20,
             *       10,
             *       5,
             *       1
             *     ]
             */
            starting_cash_denominations: number[];
        };
        /**
         * RulesetName
         * @enum {string}
         */
        RulesetName: "universal" | "kids";
        /**
         * RulesetView
         * @description A rule set as a setup screen needs it: identified, labelled, and explained.
         *
         *     ``ruleset`` still ships whole, because the *game* screen reads flags off it
         *     (``ruleset.jail_fine``, ``ruleset.simplified_trades``) and that is a copy, not a diff.
         */
        RulesetView: {
            name: components["schemas"]["RulesetName"];
            /** Label Key */
            label_key: string;
            ruleset: components["schemas"]["Ruleset"];
            /** Flags */
            flags: components["schemas"]["RuleFlagView"][];
        };
        /**
         * SaveFile
         * @description A whole session on disk: the state, and the events that produced it (ADR-011).
         *
         *     ``GET /games/{id}/save`` answers with this and ``POST /games/load`` accepts it. It exists
         *     because a save used to be a bare ``GameState`` and a session is more than one — ``Session.log``
         *     is not a state field, so a restored game came back with its board, money and deeds exactly right
         *     and *"What's happened"* empty. Both halves of that are here now.
         *
         *     **The events are the engine's, without ``seq``.** ``LoggedEvent.seq`` is assigned by the store
         *     and nowhere else (see :mod:`kesef_server.sessions`), so a file that carried numbers would be
         *     asking the next session to honour a previous one's. The store stamps a restored log ``1..N``
         *     exactly as it stamps a live one.
         *
         *     **A bare ``GameState`` still loads.** Every file saved before ADR-011 is one, and
         *     :meth:`from_json` reads it as the state with no events. The two shapes cannot be confused: an
         *     envelope has a ``state`` field and ``GameState`` declares none, so neither validates as the other.
         *
         *     **No version of its own.** Whether a save loads is decided by ``state.schema_version``, and the
         *     events are validated by the same union the live log is built from. A second version field beside
         *     the engine's would be a second thing to keep in step and the first to go stale.
         */
        SaveFile: {
            state: components["schemas"]["GameState"];
            /**
             * Events
             * @default []
             */
            events: (components["schemas"]["TurnStarted"] | components["schemas"]["DiceRolled"] | components["schemas"]["TokenMoved"] | components["schemas"]["CashChanged"] | components["schemas"]["RentCharged"] | components["schemas"]["PropertyAcquired"] | components["schemas"]["AuctionStarted"] | components["schemas"]["BidPlaced"] | components["schemas"]["BidderWithdrew"] | components["schemas"]["AuctionEnded"] | components["schemas"]["CardDrawn"] | components["schemas"]["SentToJail"] | components["schemas"]["LeftJail"] | components["schemas"]["BuildingChanged"] | components["schemas"]["MortgageChanged"] | components["schemas"]["TradeProposed"] | components["schemas"]["TradeExecuted"] | components["schemas"]["TradeDeclined"] | components["schemas"]["TradeCancelled"] | components["schemas"]["DebtIncurred"] | components["schemas"]["DebtSettled"] | components["schemas"]["PlayerBankrupted"] | components["schemas"]["PhaseChanged"] | components["schemas"]["GameEnded"])[];
        };
        /**
         * SeatConfig
         * @description One seat at the table. A seat is either a person or a bot.
         *
         *     ``is_bot`` stays on the *wire* even though the engine's ``PlayerKind`` derives it from
         *     ``bot_level``: a client that sends ``is_bot: true`` and forgets the level has made a
         *     mistake, and a 422 says so instead of silently seating a human.
         */
        SeatConfig: {
            /** Name */
            name: string;
            /**
             * Is Bot
             * @default false
             */
            is_bot: boolean;
            bot_level?: components["schemas"]["BotLevel"] | null;
            /** Token */
            token: string;
            /**
             * Grammatical Gender
             * @default n
             * @enum {string}
             */
            grammatical_gender: "m" | "f" | "n";
        };
        /**
         * SellHouse
         * @description Sell buildings back to the bank at half the build cost.
         *
         *     One level at a time by default — a hotel becomes four houses, which the bank must be
         *     able to supply. ``demolish_hotel`` invokes the official "all buildings on one colour-
         *     group may be sold at once" clause instead, which is the only way off the board when
         *     the bank has run out of houses (GAP G-B3b, MON-201).
         */
        SellHouse: {
            /** Player */
            player: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "sell_house";
            /** Tile */
            tile: number;
            /**
             * Demolish Hotel
             * @default false
             */
            demolish_hotel: boolean;
        };
        /** SentToJail */
        SentToJail: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sent_to_jail";
            /** Player */
            player: number;
            /**
             * Via
             * @enum {string}
             */
            via: "tile" | "card" | "three_doubles";
        };
        /**
         * TileKind
         * @description What happens when a token lands here.
         * @enum {string}
         */
        TileKind: "go" | "property" | "railroad" | "utility" | "chance" | "community_chest" | "tax" | "jail" | "free_parking" | "go_to_jail";
        /**
         * TileLot
         * @description One tile, offered whole. The ordinary auction.
         */
        TileLot: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "tile";
            /** Tile */
            tile: number;
        };
        /**
         * TileView
         * @description One square, plus the ownability the engine derives from its kind.
         *
         *     ADR-008 says "``board: Board`` ships whole", which is *almost* enough: ``is_ownable``
         *     is a property, so pydantic drops it, and a client recomputing
         *     ``kind in {property, railroad, utility}`` has copied ``OWNABLE_KINDS`` — engine
         *     knowledge — into TypeScript. One promoted boolean is cheaper than that.
         */
        TileView: {
            /** Index */
            index: number;
            kind: components["schemas"]["TileKind"];
            /** Name Key */
            name_key: string;
            group?: components["schemas"]["ColorGroup"] | null;
            /** Price */
            price?: number | null;
            /**
             * Rent
             * @default []
             */
            rent: number[];
            /** House Cost */
            house_cost?: number | null;
            /** Mortgage */
            mortgage?: number | null;
            /** Tax */
            tax?: number | null;
            /** Is Ownable */
            is_ownable: boolean;
        };
        /** TokenMoved */
        TokenMoved: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "token_moved";
            /** Player */
            player: number;
            /** From Tile */
            from_tile: number;
            /** To Tile */
            to_tile: number;
            /**
             * Forward
             * @default true
             */
            forward: boolean;
            /**
             * Passed Go
             * @default false
             */
            passed_go: boolean;
        };
        /** TradeCancelled */
        TradeCancelled: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "trade_cancelled";
            offer: components["schemas"]["TradeOffer"];
            /**
             * By
             * @default proposer
             * @enum {string}
             */
            by: "proposer" | "system";
        };
        /** TradeDeclined */
        TradeDeclined: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "trade_declined";
            offer: components["schemas"]["TradeOffer"];
        };
        /** TradeExecuted */
        TradeExecuted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "trade_executed";
            offer: components["schemas"]["TradeOffer"];
        };
        /**
         * TradeFrame
         * @description A proposed trade awaiting the recipient's answer.
         */
        TradeFrame: {
            resume: components["schemas"]["Phase"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "trade";
            offer: components["schemas"]["TradeOffer"];
        };
        /**
         * TradeFrameView
         * @description A verbatim copy. Declared so the union below is homogeneous.
         */
        TradeFrameView: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "trade";
            resume: components["schemas"]["Phase"];
            offer: components["schemas"]["TradeOffer"];
        };
        /** TradeOffer */
        TradeOffer: {
            /** Proposer */
            proposer: number;
            /** Recipient */
            recipient: number;
            give: components["schemas"]["TradeSide"];
            receive: components["schemas"]["TradeSide"];
        };
        /**
         * TradeProposed
         * @description Without this the WebSocket stream never carried the offer, so a replay could not
         *     reconstruct the pending trade (GAP G-16).
         */
        TradeProposed: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "trade_proposed";
            offer: components["schemas"]["TradeOffer"];
        };
        /**
         * TradeSide
         * @description What one party puts on the table.
         *
         *     ``extra="forbid"`` for the same reason ``_CommandBase`` has it: this is command payload, and
         *     a misspelled ``cash`` that is ignored offers nothing while looking like a full offer.
         */
        TradeSide: {
            /**
             * Cash
             * @default 0
             */
            cash: number;
            /**
             * Tiles
             * @default []
             */
            tiles: number[];
            /**
             * Jail Cards
             * @default []
             */
            jail_cards: components["schemas"]["Deck"][];
        };
        /** TurnStarted */
        TurnStarted: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "turn_started";
            /** Player */
            player: number;
            /** Turn Number */
            turn_number: number;
        };
        /** UnmortgageProperty */
        UnmortgageProperty: {
            /** Player */
            player: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "unmortgage_property";
            /** Tile */
            tile: number;
        };
        /** UseJailCard */
        UseJailCard: {
            /** Player */
            player: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "use_jail_card";
        };
        /** WithdrawFromAuction */
        WithdrawFromAuction: {
            /** Player */
            player: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "withdraw_from_auction";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_boards_boards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardSummary"][];
                };
            };
        };
    };
    list_rulesets_rulesets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulesetView"][];
                };
            };
        };
    };
    create_game_games_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameView"];
                };
            };
            /** @description That game_id is already live. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Refused by a per-client bound (MON-905). `error.too_many_requests` carries `retry_after` in seconds; `error.too_many_games` means this client already holds `max_sessions_per_client` live games and waiting will not help. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An engine failure. `error.engine_failure` — a defect on this side of the wire. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Session cap reached. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    load_game_games_load_post: {
        parameters: {
            query?: {
                /** @description What to do when this save's game_id is already live (ADR-011). */
                if_exists?: components["schemas"]["IfExists"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveFile"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameView"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Refused by a per-client bound (MON-905). `error.too_many_requests` carries `retry_after` in seconds; `error.too_many_games` means this client already holds `max_sessions_per_client` live games and waiting will not help. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An engine failure. `error.engine_failure` — a defect on this side of the wire. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_game_games__game_id__get: {
        parameters: {
            query?: {
                /** @description Replay the events after this cursor. */
                since?: number | null;
            };
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameView"];
                };
            };
            /** @description No game with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rejected, with an i18n key. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An engine failure. `error.engine_failure` — a defect on this side of the wire. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_game_games__game_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Refused by a per-client bound (MON-905). `error.too_many_requests` carries `retry_after` in seconds; `error.too_many_games` means this client already holds `max_sessions_per_client` live games and waiting will not help. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An engine failure. `error.engine_failure` — a defect on this side of the wire. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    save_game_games__game_id__save_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveFile"];
                };
            };
            /** @description No game with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rejected, with an i18n key. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An engine failure. `error.engine_failure` — a defect on this side of the wire. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    submit_command_games__game_id__commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameView"];
                };
            };
            /** @description No game with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rejected, with an i18n key. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An engine failure. `error.engine_failure` — a defect on this side of the wire. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    validate_command_games__game_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalityView"];
                };
            };
            /** @description No game with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rejected, with an i18n key. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description An engine failure. `error.engine_failure` — a defect on this side of the wire. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    game_event_stream: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching protocols. Every frame that follows is one LoggedEvent. */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoggedEvent"];
                };
            };
            /** @description No such game; the socket closes with code 4404. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
